import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  products: [
    {
      id: 1,
      name: 'Heladera',
      description: 'Heladera no frost',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail:
        'https://pampahogar.com.ar/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/h/e/heladera-samsung-rt38-1.jpg',
      price: 10000,
      currency: '$',
      pictures: ['https://pampahogar.com.ar/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/h/e/heladera-samsung-rt38-1.jpg'],
      promoPrice: 9000,
      promo: true,
      rating: 5,
      category: 'Electrodomesticos',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 2,
      name: 'Heladera',
      description:
        'Heladera no frost,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 19psum passages, and more recently with ',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail: 'https://monchitime.com/www/wp-content/uploads/2014/01/Chef_Collection_Range.jpg',
      price: 10000,
      currency: '$',
      pictures: ['https://monchitime.com/www/wp-content/uploads/2014/01/Chef_Collection_Range.jpg'],
      promoPrice: 9000,
      promo: true,
      rating: 5,
      category: 'Recetarios',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 3,
      name: 'PRIMERA CONSULTA + ARMADO DE PLAN PERSONALIZADO',
      description:
        'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularism passages, and more recently with ',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail:
        'https://pampahogar.com.ar/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/h/e/heladera-samsung-rt38-1.jpg',
      price: 10000,
      currency: '$',
      pictures: ['https://pampahogar.com.ar/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/h/e/heladera-samsung-rt38-1.jpg'],
      promoPrice: 9000,
      promo: false,
      rating: 5,
      category: 'Mosaicos',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 4,
      name: 'Heladera',
      description:
        '-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable s',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail: 'https://jumboargentina.vtexassets.com/arquivos/ids/607890/Lavarropas-Samsung-Ww70m0nhuu-7kg-Silver-1-854503.jpg?v=637383284248300000',
      price: 10000,
      currency: '$',
      pictures: ['https://jumboargentina.vtexassets.com/arquivos/ids/607890/Lavarropas-Samsung-Ww70m0nhuu-7kg-Silver-1-854503.jpg?v=637383284248300000'],
      promoPrice: 9000,
      promo: true,
      rating: 5,
      category: 'Pack ahorro',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 5,
      name: 'Heladera',
      description:
        're going to use a passage of Lorem Ipsum, you need to be sure there isnt anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail: 'https://http2.mlstatic.com/D_NQ_NP_704990-MLA42568625327_072020-O.jpg',
      price: 10000,
      currency: '$',
      pictures: ['https://http2.mlstatic.com/D_NQ_NP_704990-MLA42568625327_072020-O.jpg'],
      promoPrice: 9000,
      promo: false,
      rating: 5,
      category: 'Consultas Online',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 6,
      name: 'Heladera',
      description:
        'or those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,',
      location: 'USA',
      stock: 10,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail: 'https://hendel-r7d8odghj1.stackpathdns.com/media/catalog/product/cache/0c3e9ac8430b5a3e77d1544ae1698a10/1/0/103895.jpg',
      price: 10000,
      currency: '$',
      pictures: ['https://hendel-r7d8odghj1.stackpathdns.com/media/catalog/product/cache/0c3e9ac8430b5a3e77d1544ae1698a10/1/0/103895.jpg'],
      promoPrice: 9000,
      promo: false,
      rating: 5,
      category: 'Guias',
      warningNote: '1 año de garantia',
      inCart: 0,
    },
    {
      id: 7,
      name: 'Aire acondicionado',
      description:
        'or those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form,',
      location: 'USA',
      stock: 5,
      size: '100',
      color: 'black',
      displayColor: '#000000',
      displayThumbnail: 'https://http2.mlstatic.com/D_NQ_NP_747872-MLA31585977410_072019-O.jpg',
      price: 6000,
      currency: '$',
      pictures: ['https://http2.mlstatic.com/D_NQ_NP_747872-MLA31585977410_072019-O.jpg'],
      promoPrice: 5000,
      promo: true,
      rating: 5,
      category: 'Electrodomesticos',
      warningNote: '2 años de garantia',
      inCart: 0,
    },
  ],
};
const productSlice = createSlice({
  name: 'products',
  initialState,
  reducers: {},
});

export const getAllProducts = (state) => state.products.products;
export default productSlice.reducer;
